name: Deploy to AWS

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: S3 Bucket sync and invalidate CloudFront cache
      uses: kersvers/s3-sync-with-cloudfront-invalidation@v1.0.0
      with:
        args: --follow-symlinks --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'build'